### ISSUE TITLE
NRE in 'Fix All' -> Solution

### ISSUE THREAD

**Issue by deniszykov** [bkoelman/ResharperCodeContractNullability#41]
**Version Used**: 
2.0.0

**Steps to Reproduce**:

1. Have a huge project
2. Have a nullable = enabled + JetBrains.Annotations around a project
1. Choose 'Convert to C# Syntax' -> Solution

**Expected Behavior**:
No error.

**Actual Behavior**:
```console
System.ArgumentNullException : Value cannot be null.
Parameter name: declarationSymbol
   at CodeContractNullability.Conversion.NullConversionScope..ctor(NullConversionContext context,SyntaxNode declarationSyntax,ISymbol declarationSymbol)
   at async CodeContractNullability.NullableReferenceTypeConversionCodeFixProvider.ChangeSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionInternalAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetChangedDocumentsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetDocumentIdToChangedDocuments(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.TryMergeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.TryGetMergedFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
```

**Comment by bkoelman** [comment]
Thanks for reporting this. I'm unable to reproduce, unfortunately. Can you narrow this down to a single project, then to the affected source file and submit a small repro?

**Comment by deniszykov** [comment]
This [code](https://github.com/bkoelman/ResharperCodeContractNullability/blob/f96173f3788f034d4bbec66ee62286802f9b57ed/src/CodeContractNullability/CodeContractNullability/NullableReferenceTypeConversionCodeFixProvider.cs#L68) could give null because it based on [GetDeclaredSymbolCore](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.semanticmodel.getdeclaredsymbolcore?view=roslyn-dotnet#Microsoft_CodeAnalysis_SemanticModel_GetDeclaredSymbolCore_Microsoft_CodeAnalysis_SyntaxNode_System_Threading_CancellationToken_) which could return null.

**Comment by bkoelman** [comment]
Yes, but almost everything in roslyn returns null under some circumstances. For example, when typing code that is not yet valid syntax. The point is to validate upfront and skip analysis in those cases, instead of sprinkling the code full with null checks everywhere. So the question is: what piece of code is causing this?

**Comment by bkoelman** [comment]
> You could skip syntax which is not declaration, or generate warning/message to output.

As far as I'm aware, analysis is configured to only run on type/member/parameter declarations, so I suspect something else is causing the error.

**Comment by deniszykov** [comment]
I will try to locate this error tomorrow.

**Comment by bkoelman** [comment]
Thanks. The next steps should make it easier to find the source file that causes this:
- clone the repo and open in VS
- put a try/catch around the line from error stack trace. Rethrow in the catch block, but but a breakpoint on it
- press F5 (assuming vsix as startup project), which launches a second VS instance with the debugger attached
- in the second instance, open your solution and run the codefix
- when the breakpoint hits, inspect properties of syntax node to find the file path and line number where it is declared

Note that the second VS instance will be very slow with attached debugger, so it may take some time to get there. Hope this helps.

**Comment by deniszykov** [comment]
BTW, Thanks for your package. It helped me a lot.

**Comment by bkoelman** [comment]
Thank you for investigating the root cause. I can repro the problem now and the fix is coming soon.

Glad to hear my package is useful to you. Please thank me by adding a star to the repo. :)
